# Generated by Django 4.0 on 2022-01-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EgresadosMaestria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerequisito',
            name='ruta',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
